name: Release

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
          cache: 'npm'
      - run: python3 -m pip install setuptools
      - run: npm install
      - name: generate version
        run: echo "${{ github.ref }}" | sed 's/refs\/tags\/v//g' | xargs npm version --no-git-tag-version
      - run: npm run build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*.dmg,dist/*.exe,dist/*.blockmap,dist/*.deb,dist/*.AppImage,dist/*.pacman'
          token: ${{ github.token }}
          draft: true
